export const HEADER_X_REQUEST_ID = 'x-request-id';

export const APP_ERROR_CODE = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SEAT_NOT_FOUND: 'SEAT_NOT_FOUND',
  SEAT_ALREADY_RESERVED: 'SEAT_ALREADY_RESERVED',
} as const;
